name: ci-cm-latest

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'master'
    tags:
      # - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
      - '1.2.*'
      - 'v1.2.*'
      
  pull_request:
    branches:
      - "master/**"
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    # branches:
    #   - 'main'
    #   - 'release-*'
    #   - 'DOC-*'
    #   - 'hotfix-*'

permissions: # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: write
  discussions: write
  packages: write

jobs:
  docker-bake-all-latest:
    name: docker-bake-all-latest
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-latest.yml
    # if: ${{ github.ref_type != 'tag' }}
    if: ${{ ( github.event_name == 'push' && github.ref_type != 'tag' && github.ref == 'refs/heads/master' ) || github.base_ref == 'master' }}
    with:
      push_remote_flag: ${{ github.ref == 'refs/heads/master' }}
    #   push_remote_flag: ${{ github.event.pull_request.merged == true }}
      docker_bake_targets: 'image-basic'
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  docker-bake-alpine-latest:
    name: docker-bake-alpine-latest
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-latest.yml
    # if: ${{ github.ref_type != 'tag' }}
    if: ${{ ( github.event_name == 'push' && github.ref_type != 'tag' && github.ref == 'refs/heads/master' ) || github.base_ref == 'master' }}
    with:
      docker_bake_targets: 'image-alpine'
      push_remote_flag: true # for flavor latest only one image by `image-basic-all` so no need push remote
      docker-metadata-flavor-suffix: '-alpine' # default is '', can add as: -alpine -debian
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  docker-bake-debian-latest:
    name: docker-bake-debian-latest
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-latest.yml
    # if: ${{ github.ref_type != 'tag' }}
    if: ${{ ( github.event_name == 'push' && github.ref_type != 'tag' && github.ref == 'refs/heads/master' ) || github.base_ref == 'master' }}
    with:
      docker_bake_targets: 'image-debian'
      push_remote_flag: true # for flavor latest only one image by `image-basic-all` so no need push remote
      docker-metadata-flavor-suffix: '-debian' # default is '', can add as: -alpine -debian
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  ### deploy tag start

  docker-bake-alpine-all-tag:
    name: docker-bake-alpine-all-tag
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    with:
      docker_bake_targets: 'image-alpine'
      docker-metadata-flavor-suffix: '-alpine' # default is '', can add as: -alpine -debian
      # push_remote_flag: true # default is true
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  docker-bake-debian-all-tag:
    name: docker-bake-debian-all-tag
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    with:
      docker_bake_targets: 'image-debian'
      docker-metadata-flavor-suffix: '-debian' # default is '', can add as: -alpine -debian
      # push_remote_flag: true # default is true
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  docker-bake-all-tag:
    name: docker-bake-all-tag
    needs:
      - docker-bake-alpine-all-tag
      - docker-bake-debian-all-tag
    uses: ./.github/workflows/docker-buildx-bake-cm-latest-hubdocker-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    with:
      docker_bake_targets: 'image-basic'
      docker-metadata-flavor-suffix: '' # default is '', can add as: -alpine -debian
      # push_remote_flag: true # default is true
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  ### deploy tag end 